### ISSUE TITLE
Automatic log clean-up fails

### ISSUE THREAD

**Issue by anotherHoffmann** [m-moris/log4j2-azure-blob-appender#11]
Hi there,

I have been using your appender for some time now and it works great.

But the automatic clean-up of old log files does not work and I get the following error message in the log:

```2021-11-22T09:57:19
Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (409) Conflict. ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.ListBlobsSegmented(String prefix, Boolean useFlatBlobListing, BlobListingDetails blobListingDetails, Nullable`1 maxResults, BlobContinuationToken currentToken, BlobRequestOptions options, OperationContext operationContext)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.CleanupOldBlobLogs(Object state)
Request Information
RequestID:f56ee9f9-301e-005a-6187-df9970000000
RequestDate:Mon, 22 Nov 2021 09:57:19 GMT
StatusMessage:The type of a blob in the container is unrecognized by this version.
ErrorCode:FeatureVersionMismatch
```

Can you implement a fix for this? Alternatively I would be grateful for pointing me in the right direction, so I can fix it myself.

Have a great day!

**Comment by m-moris** [comment]
@anotherHoffmann 

Thanks for the report.
I would appreciate it if you could send me a pull request or a diff of the fix.

**Comment by anotherHoffmann** [comment]
According to [this](https://techcommunity.microsoft.com/t5/azure-paas-blog/featureversionmismatch-while-performing-a-list-blob-operation/ba-p/794279), the fix would be to update the azure-storage dependency. I cannot test this, since I am on vacation, but it would be worth a try.
